// @duralux/ui/antd — componentes antd con el tema Duralux. antd y dayjs son peers opcionales.
export { DuraluxAntdProvider, type DuraluxAntdProviderProps } from './DuraluxAntdProvider'
export { antdConfigFor } from './config'
export { DatePicker, RangePicker, DateRangeFilter, DATE_FORMAT, type DatePickerProps, type RangePickerProps } from './pickers'
export { TreeSelect, Cascader, FileDrop, type TreeSelectProps, type CascaderProps, type FileDropProps } from './fields'
export { RangeSlider, NumberInput, AutoComplete, Mentions, ColorPicker, type RangeSliderProps, type NumberInputProps, type AutoCompleteProps, type MentionsProps, type ColorPickerProps } from './inputs'
export { TimePicker, TimeRangePicker, Calendar, TIME_FORMAT, type TimePickerProps, type TimeRangePickerProps, type CalendarProps } from './time'
export { Transfer, CheckTree, type TransferItem, type TransferProps, type CheckTreeProps } from './selection'
export { Splitter, Tour, ImagePreview, type SplitterProps, type SplitterPanelProps, type TourProps, type TourStepProps, type ImagePreviewProps } from './overlay'
export { formatNumberEsCL, parseNumberEsCL, duraluxColorPresets, SPLITTER_PANEL_MIN, dateRangePresets, type DateRangePreset } from './defaults'
