// Genera todos los artefactos de tokens desde tokens/tokens.json (formato W3C DTCG).
//   node scripts/generate-tokens.mjs           → escribe
//   node scripts/generate-tokens.mjs --check   → falla si hay deriva o pares sin contraste AA
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const CSS_START = '/* BEGIN GENERATED SEMANTIC TOKENS */'
const CSS_END = '/* END GENERATED SEMANTIC TOKENS */'
const HEADER = 'Generated by scripts/generate-tokens.mjs from tokens/tokens.json. Do not edit by hand.'

// Orden fijo de los colores base: define el orden de salida y la API de semanticColors.
const COLOR_NAMES = ['primary', 'secondary', 'success', 'danger', 'warning', 'info', 'indigo', 'bg', 'body', 'canvas', 'teal', 'dark', 'darken', 'light']
const WIDGET_COLOR_NAMES = ['primary', 'success', 'danger', 'warning', 'info', 'teal', 'indigo', 'secondary', 'dark']
const STAT_COLOR_NAMES = WIDGET_COLOR_NAMES.filter(name => name !== 'dark')
const TONES = ['primary', 'secondary', 'success', 'danger', 'warning', 'info', 'teal', 'indigo']
const THEMES = ['light', 'dark', 'navy']
const THEME_COLOR_KEYS = ['text', 'muted', 'text-subtle', 'text-inverse', 'primary-text', 'code', 'surface', 'surface-subtle', 'surface-raised', 'surface-sunken', 'overlay', 'border', 'border-strong', 'focus', 'focus-ring-color']
// Pares texto/fondo que deben cumplir AA (4,5:1) en cada tema.
const TEXT_ON = ['surface', 'surface-subtle', 'surface-raised']
const TEXT_KEYS = ['text', 'muted', 'primary-text', 'code']
const SUBTLE_MIN = 3 // text-subtle: placeholders e info secundaria no esencial

const HEX = /^#[0-9a-f]{6}$/i
const log = (...m) => console.log('[tokens]', ...m)

// ── Lectura y validación ───────────────────────────────────────────────────
export function readTokens(root = ROOT) {
  const path = join(root, 'tokens/tokens.json')
  const tokens = JSON.parse(readFileSync(path, 'utf8'))
  const base = tokens?.color?.base ?? {}
  const missing = COLOR_NAMES.filter(name => !base[name])
  if (missing.length) throw new Error(`${path}: faltan colores base: ${missing.join(', ')}`)
  const extra = Object.keys(base).filter(name => !COLOR_NAMES.includes(name))
  if (extra.length) throw new Error(`${path}: colores base no soportados: ${extra.join(', ')}`)
  for (const name of COLOR_NAMES) {
    if (!HEX.test(base[name].$value)) throw new Error(`${path}: color.base.${name} inválido: ${base[name].$value}`)
  }
  for (const theme of THEMES) {
    const t = tokens.theme?.[theme]
    if (!t) throw new Error(`${path}: falta theme.${theme}`)
    const absent = THEME_COLOR_KEYS.filter(key => !t[key])
    if (absent.length) throw new Error(`${path}: theme.${theme} sin ${absent.join(', ')}`)
  }
  return tokens
}

const v = token => token.$value
const baseColors = tokens => Object.fromEntries(COLOR_NAMES.map(name => [name, v(tokens.color.base[name]).toLowerCase()]))

// ── Color ──────────────────────────────────────────────────────────────────
function channels(hex) {
  return [1, 3, 5].map(offset => Number.parseInt(hex.slice(offset, offset + 2), 16))
}
const rgbChannels = hex => channels(hex).join(', ')

export function mixHex(a, b, weightOfA) {
  const [ca, cb] = [channels(a), channels(b)]
  return `#${ca.map((x, i) => Math.round(x * weightOfA + cb[i] * (1 - weightOfA)).toString(16).padStart(2, '0')).join('')}`
}

function luminance(hex) {
  const [r, g, b] = channels(hex).map(c => {
    const s = c / 255
    return s <= 0.04045 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4
  })
  return 0.2126 * r + 0.7152 * g + 0.0722 * b
}

export function contrastRatio(a, b) {
  const [la, lb] = [luminance(a), luminance(b)].sort((x, y) => y - x)
  return (la + 0.05) / (lb + 0.05)
}

/** Valores resueltos de un tema: colores + derivados por tono. */
function resolveTheme(tokens, theme) {
  const t = tokens.theme[theme]
  const base = baseColors(tokens)
  const mix = v(t.mix)
  const surface = v(t.surface)
  const out = Object.fromEntries(THEME_COLOR_KEYS.map(key => [key, v(t[key])]))
  for (const tone of TONES) {
    out[`status-${tone}`] = v(t.status[tone])
    out[`${tone}-soft`] = mixHex(base[tone], surface, mix.soft)
    out[`${tone}-border`] = mixHex(base[tone], surface, mix.border)
  }
  out.selection = mixHex(base.primary, surface, mix.selection)
  out.shadow = Object.fromEntries(Object.entries(t.shadow).map(([k, token]) => [k, v(token)]))
  return out
}

export function checkContrast(tokens) {
  const failures = []
  for (const theme of THEMES) {
    const r = resolveTheme(tokens, theme)
    const pairs = []
    for (const bg of TEXT_ON) {
      for (const fg of TEXT_KEYS) pairs.push([fg, bg, 4.5])
      for (const tone of TONES) pairs.push([`status-${tone}`, bg, 4.5])
      pairs.push(['text-subtle', bg, SUBTLE_MIN])
    }
    for (const tone of TONES) pairs.push([`status-${tone}`, `${tone}-soft`, 4.5])
    for (const [fg, bg, min] of pairs) {
      if (!HEX.test(r[fg]) || !HEX.test(r[bg])) continue
      const ratio = contrastRatio(r[fg], r[bg])
      if (ratio < min) failures.push(`${theme}: ${fg} sobre ${bg} = ${ratio.toFixed(2)} (< ${min})`)
    }
  }
  return failures
}

// ── CSS ────────────────────────────────────────────────────────────────────
const cssName = path => path.join('-')

function scaleDeclarations(tokens) {
  const d = []
  const push = (prefix, group) => {
    for (const [key, token] of Object.entries(group)) d.push(`--gcu-${prefix}-${key}:${v(token)}`)
  }
  for (const [hue, steps] of Object.entries(tokens.color.palette)) push(hue, steps)
  push('space', tokens.space)
  push('radius', tokens.radius)
  push('control-h', tokens.control.height)
  push('font-size', tokens.font.size)
  push('line-height', tokens.font['line-height'])
  push('font-weight', tokens.font.weight)
  push('tracking', tokens.font.tracking)
  push('duration', tokens.motion.duration)
  push('ease', tokens.motion.easing)
  push('z', tokens['z-index'])
  d.push(`--gcu-press-scale:${v(tokens.motion['press-scale'])}`)
  d.push(`--gcu-font-sans:${v(tokens.font.family.sans)}`)
  d.push(`--gcu-font-mono:${v(tokens.font.family.mono)}`)
  return d
}

function themeDeclarations(tokens, theme) {
  const r = resolveTheme(tokens, theme)
  const d = THEME_COLOR_KEYS.map(key => `--gcu-${key}:${r[key]}`)
  for (const tone of TONES) {
    d.push(`--gcu-status-${tone}:${r[`status-${tone}`]}`)
    d.push(`--gcu-${tone}-soft:${r[`${tone}-soft`]}`)
    d.push(`--gcu-${tone}-border:${r[`${tone}-border`]}`)
    d.push(`--gcu-${tone}-text:var(--gcu-status-${tone})`)
  }
  d.push(`--gcu-selection:${r.selection}`)
  for (const [k, value] of Object.entries(r.shadow)) d.push(`--gcu-shadow-${k}:${value}`)
  // Compatibilidad: --gcu-shadow (único) = nivel 1.
  d.push('--gcu-shadow:var(--gcu-shadow-1)')
  d.push("--gcu-focus-ring:0 0 0 2px var(--gcu-surface),0 0 0 4px var(--gcu-focus-ring-color)")
  return d
}

const block = (selector, declarations) => `${selector}{\n  ${declarations.join(';')};\n}`

export function renderGeneratedCss(tokens) {
  const colors = baseColors(tokens)
  const baseDecl = [
    ...COLOR_NAMES.map(name => `--gcu-${name}:${colors[name]}`),
    ...COLOR_NAMES.map(name => `--gcu-${name}-rgb:${rgbChannels(colors[name])}`),
    '--gcu-radius:10px',
    '--gcu-on-primary:#fff;--gcu-on-secondary:#fff;--gcu-on-success:var(--gcu-darken);--gcu-on-danger:var(--gcu-darken);--gcu-on-warning:var(--gcu-darken);--gcu-on-info:var(--gcu-darken);--gcu-on-teal:var(--gcu-darken);--gcu-on-indigo:#fff;--gcu-on-dark:#fff;--gcu-on-darken:#fff;--gcu-on-light:var(--gcu-dark)',
    '--gcu-font:var(--gcu-font-sans)',
    ...scaleDeclarations(tokens),
  ]
  const nestedNavy = '[data-gcu-theme="navy"] .gcu-theme:not([data-gcu-theme="light"]):not([data-gcu-theme="dark"])'
  return [
    CSS_START,
    `/* ${HEADER} */`,
    block(':root,.gcu-theme,[data-gcu-theme="light"]', [...baseDecl, ...themeDeclarations(tokens, 'light')]),
    block('[data-gcu-theme="dark"],.app-skin-dark', themeDeclarations(tokens, 'dark')),
    '/* Dark theme override: .gcu-theme may re-declare light vars in its own scope. */',
    block('.app-skin-dark .gcu-theme:not([data-gcu-theme="light"]):not([data-gcu-theme="navy"])', themeDeclarations(tokens, 'dark')),
    '/* Navy gana a dark: <html> en navy también lleva .app-skin-dark. */',
    block(`[data-gcu-theme="navy"],${nestedNavy}`, themeDeclarations(tokens, 'navy')),
    '@media (prefers-reduced-motion:reduce){:root,.gcu-theme,[data-gcu-theme]{--gcu-duration-instant:0ms;--gcu-duration-fast:0ms;--gcu-duration-base:0ms;--gcu-duration-slow:0ms;--gcu-press-scale:1}}',
    CSS_END,
  ].join('\n')
}

// ── SCSS / TS / antd ───────────────────────────────────────────────────────
function renderGeneratedScss(tokens) {
  const colors = baseColors(tokens)
  const lines = [`// ${HEADER}`]
  for (const name of COLOR_NAMES) lines.push(`$semantic-${name}: ${colors[name]};`)
  lines.push('')
  for (const name of COLOR_NAMES) lines.push(`$semantic-${name}-rgb: ${rgbChannels(colors[name])};`)
  lines.push('', '$semantic-widget-colors: (')
  for (const name of WIDGET_COLOR_NAMES) lines.push(`\t"${name}": $semantic-${name},`)
  lines.push(');', '', '$semantic-stat-colors: (')
  for (const name of STAT_COLOR_NAMES) lines.push(`\t"${name}": $semantic-${name},`)
  lines.push(');', '')
  // Escalas para Bootstrap/theme (valores estáticos: Sass necesita literales).
  for (const [k, t] of Object.entries(tokens.radius)) lines.push(`$token-radius-${k}: ${v(t)};`)
  for (const [k, t] of Object.entries(tokens.control.height)) lines.push(`$token-control-h-${k}: ${v(t)};`)
  for (const [k, t] of Object.entries(tokens.theme.light.shadow)) lines.push(`$token-shadow-${k}: ${v(t)};`)
  lines.push(`$token-font-sans: ${v(tokens.font.family.sans)};`)
  lines.push(`$token-font-mono: ${v(tokens.font.family.mono)};`)
  for (const theme of THEMES) {
    const r = resolveTheme(tokens, theme)
    for (const key of ['text', 'muted', 'code', 'surface', 'surface-subtle', 'border', 'border-strong']) {
      lines.push(`$token-${theme}-${key}: ${r[key]};`)
    }
    lines.push(`$token-${theme}-status-danger: ${r['status-danger']};`)
  }
  return `${lines.join('\n')}\n`
}

function renderSemanticTs(tokens) {
  const colors = baseColors(tokens)
  const entries = COLOR_NAMES.map(name => `  ${name}: '${colors[name]}',`).join('\n')
  return `/**\n * ${HEADER}\n */\nexport const semanticColors = {\n${entries}\n} as const\n\nexport type SemanticColorName = keyof typeof semanticColors\n`
}

function renderTokensTs(tokens) {
  const flat = group => Object.fromEntries(Object.entries(group).map(([k, t]) => [k, v(t)]))
  const themes = Object.fromEntries(THEMES.map(theme => {
    const r = resolveTheme(tokens, theme)
    const { shadow, ...colors } = r
    return [theme, { colors, shadow }]
  }))
  const data = {
    palette: Object.fromEntries(Object.entries(tokens.color.palette).map(([hue, steps]) => [hue, flat(steps)])),
    space: flat(tokens.space),
    radius: flat(tokens.radius),
    controlHeight: flat(tokens.control.height),
    font: {
      family: flat(tokens.font.family),
      size: flat(tokens.font.size),
      lineHeight: flat(tokens.font['line-height']),
      weight: flat(tokens.font.weight),
      tracking: flat(tokens.font.tracking),
    },
    motion: { duration: flat(tokens.motion.duration), easing: flat(tokens.motion.easing), pressScale: v(tokens.motion['press-scale']) },
    zIndex: flat(tokens['z-index']),
    themes,
  }
  return `/**\n * ${HEADER}\n */\nexport const designTokens = ${JSON.stringify(data, null, 2)} as const\n\nexport type DesignTokens = typeof designTokens\nexport type ThemeName = keyof typeof designTokens.themes\n`
}

function renderAntdTs(tokens) {
  const base = baseColors(tokens)
  const px = value => Number.parseInt(value, 10)
  const themes = Object.fromEntries(THEMES.map(theme => {
    const r = resolveTheme(tokens, theme)
    return [theme, {
      dark: theme !== 'light',
      token: {
        colorPrimary: base.primary,
        colorSuccess: base.success,
        colorWarning: base.warning,
        colorError: base.danger,
        colorInfo: base.info,
        colorText: r.text,
        colorTextSecondary: r.muted,
        colorTextTertiary: r.muted,
        colorTextDescription: r.muted,
        // antd usa grises de 1,8:1 para placeholders y días fuera de mes; text-subtle cumple 3:1+.
        colorTextPlaceholder: r['text-subtle'],
        colorTextDisabled: r['text-subtle'],
        colorBgContainer: r.surface,
        colorBgElevated: r['surface-raised'],
        colorBgLayout: r['surface-subtle'],
        colorBorder: r['border-strong'],
        colorBorderSecondary: r.border,
        borderRadius: px(v(tokens.radius.md)),
        borderRadiusLG: px(v(tokens.radius.lg)),
        borderRadiusSM: px(v(tokens.radius.sm)),
        controlHeight: px(v(tokens.control.height.md)),
        controlHeightSM: px(v(tokens.control.height.sm)),
        controlHeightLG: px(v(tokens.control.height.lg)),
        fontFamily: v(tokens.font.family.sans),
        fontSize: px(v(tokens.font.size.sm)),
        // Popups (calendario, selects) sobre los modales Duralux: un DatePicker dentro de un Modal debe verse.
        zIndexPopupBase: v(tokens['z-index'].popover),
        boxShadow: r.shadow['2'],
        boxShadowSecondary: r.shadow['3'],
        motionDurationFast: `${px(v(tokens.motion.duration.instant)) / 1000}s`,
        motionDurationMid: `${px(v(tokens.motion.duration.fast)) / 1000}s`,
        motionDurationSlow: `${px(v(tokens.motion.duration.base)) / 1000}s`,
      },
    }]
  }))
  return `/**\n * ${HEADER}\n * Objeto ThemeConfig de antd por tema, sin importar antd (lo consume @duralux/ui/antd).\n * \`dark: true\` indica usar theme.darkAlgorithm.\n */\nexport const antdThemes = ${JSON.stringify(themes, null, 2)} as const\n`
}

// ── Artefactos ─────────────────────────────────────────────────────────────
const PATHS = {
  semanticTs: 'src/generated/semantic-colors.ts',
  tokensTs: 'src/generated/tokens.ts',
  antdTs: 'src/generated/antd-theme.ts',
  scss: 'scss/themes/_semantic-tokens.generated.scss',
  tokensCss: 'src/styles/tokens.css',
  css: 'src/styles/grancrm-ui.css',
}

function expectedArtifacts(tokens) {
  const css = renderGeneratedCss(tokens)
  return {
    semanticTs: renderSemanticTs(tokens),
    tokensTs: renderTokensTs(tokens),
    antdTs: renderAntdTs(tokens),
    scss: renderGeneratedScss(tokens),
    tokensCss: `${css}\n`,
    css,
  }
}

function replaceGeneratedCss(content, generatedBlock) {
  const start = content.indexOf(CSS_START)
  const end = content.indexOf(CSS_END)
  if (start === -1 || end === -1 || end < start) throw new Error('grancrm-ui.css no tiene un bloque de tokens generado completo')
  return `${content.slice(0, start)}${generatedBlock}${content.slice(end + CSS_END.length)}`
}

const readOr = (path, fallback) => {
  try { return readFileSync(path, 'utf8') } catch { return fallback }
}

export function checkArtifacts(root = ROOT) {
  const tokens = readTokens(root)
  const expected = expectedArtifacts(tokens)
  const mismatches = []
  for (const kind of ['semanticTs', 'tokensTs', 'antdTs', 'scss', 'tokensCss']) {
    if (readOr(join(root, PATHS[kind]), null) !== expected[kind]) mismatches.push(join(root, PATHS[kind]))
  }
  const css = readOr(join(root, PATHS.css), '')
  const start = css.indexOf(CSS_START)
  const end = css.indexOf(CSS_END)
  const actual = start !== -1 && end >= start ? css.slice(start, end + CSS_END.length) : null
  if (actual !== expected.css) mismatches.push(`${join(root, PATHS.css)} (${CSS_START} block)`)

  if (!readOr(join(root, 'src/tokens.ts'), '').includes("from './generated/semantic-colors'")) {
    mismatches.push(`${join(root, 'src/tokens.ts')} (generated semantic import)`)
  }
  if (!readOr(join(root, 'scss/themes/_bs-custom-variables.scss'), '').includes('@import "./semantic-tokens.generated";')) {
    mismatches.push(`${join(root, 'scss/themes/_bs-custom-variables.scss')} (generated semantic import)`)
  }
  for (const failure of checkContrast(tokens)) mismatches.push(`contraste: ${failure}`)
  return mismatches
}

export function writeArtifacts(root = ROOT) {
  const tokens = readTokens(root)
  const expected = expectedArtifacts(tokens)
  for (const kind of ['semanticTs', 'tokensTs', 'antdTs', 'scss', 'tokensCss']) {
    const path = join(root, PATHS[kind])
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, expected[kind])
  }
  const cssPath = join(root, PATHS.css)
  writeFileSync(cssPath, replaceGeneratedCss(readFileSync(cssPath, 'utf8'), expected.css))
  const failures = checkContrast(tokens)
  if (failures.length) log('ADVERTENCIA contraste:', failures)
}

if (resolve(process.argv[1] ?? '') === resolve(fileURLToPath(import.meta.url))) {
  if (process.argv.includes('--check')) {
    const mismatches = checkArtifacts()
    if (mismatches.length > 0) {
      console.error('[tokens] Deriva o contraste insuficiente:')
      for (const mismatch of mismatches) console.error(`- ${mismatch}`)
      process.exitCode = 1
    } else {
      log('Artefactos al día y contraste AA en light/dark/navy.')
    }
  } else {
    writeArtifacts()
    log('Artefactos generados.')
  }
}
