import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const CSS_START = '/* BEGIN GENERATED SEMANTIC TOKENS */'
const CSS_END = '/* END GENERATED SEMANTIC TOKENS */'

const COLOR_NAMES = [
  'primary',
  'secondary',
  'success',
  'danger',
  'warning',
  'info',
  'indigo',
  'bg',
  'body',
  'canvas',
  'teal',
  'dark',
  'darken',
  'light',
]
const WIDGET_COLOR_NAMES = [
  'primary',
  'success',
  'danger',
  'warning',
  'info',
  'teal',
  'indigo',
  'secondary',
  'dark',
]
const STAT_COLOR_NAMES = WIDGET_COLOR_NAMES.filter(name => name !== 'dark')

const HEX_COLOR = /^#[0-9a-f]{6}$/i
const KEBAB_NAME = /^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/

if (COLOR_NAMES.some(name => !KEBAB_NAME.test(name))) {
  throw new Error('COLOR_NAMES must use kebab-case names')
}

function readSemanticColors(root = ROOT) {
  const sourcePath = join(root, 'tokens/semantic-colors.json')
  const source = JSON.parse(readFileSync(sourcePath, 'utf8'))
  const colors = source?.colors

  if (!colors || typeof colors !== 'object' || Array.isArray(colors)) {
    throw new Error(`${sourcePath} must contain a colors object`)
  }

  const missing = COLOR_NAMES.filter(name => !Object.prototype.hasOwnProperty.call(colors, name))
  if (missing.length > 0) {
    throw new Error(`${sourcePath} is missing colors: ${missing.join(', ')}`)
  }
  const extra = Object.keys(colors).filter(name => !COLOR_NAMES.includes(name))
  if (extra.length > 0) {
    throw new Error(`${sourcePath} has unsupported colors: ${extra.join(', ')}`)
  }

  for (const name of COLOR_NAMES) {
    if (!HEX_COLOR.test(colors[name])) {
      throw new Error(`${sourcePath} has invalid ${name}: ${String(colors[name])}`)
    }
  }

  return Object.fromEntries(COLOR_NAMES.map(name => [name, colors[name].toLowerCase()]))
}

function rgbChannels(hex) {
  return [1, 3, 5].map(offset => Number.parseInt(hex.slice(offset, offset + 2), 16)).join(', ')
}

function renderGeneratedTypeScript(colors) {
  const entries = COLOR_NAMES
    .map(name => `  ${name}: '${colors[name]}',`)
    .join('\n')

  return `/**\n * Generated by scripts/generate-tokens.mjs. Do not edit by hand.\n */\nexport const semanticColors = {\n${entries}\n} as const\n\nexport type SemanticColorName = keyof typeof semanticColors\n`
}

function renderGeneratedScss(colors) {
  const variables = COLOR_NAMES
    .map(name => `$semantic-${name}: ${colors[name]};`)
    .join('\n')
  const rgbVariables = COLOR_NAMES
    .map(name => `$semantic-${name}-rgb: ${rgbChannels(colors[name])};`)
    .join('\n')
  const widgetMapEntries = WIDGET_COLOR_NAMES
    .map(name => `\t"${name}": $semantic-${name},`)
    .join('\n')
  const statMapEntries = STAT_COLOR_NAMES
    .map(name => `\t"${name}": $semantic-${name},`)
    .join('\n')

  return `// Generated by scripts/generate-tokens.mjs. Do not edit by hand.\n${variables}\n\n${rgbVariables}\n\n$semantic-widget-colors: (\n${widgetMapEntries}\n);\n\n$semantic-stat-colors: (\n${statMapEntries}\n);\n`
}

function renderGeneratedCss(colors) {
  const semanticProperties = COLOR_NAMES
    .map(name => `  --gcu-${name}:${colors[name]};`)
    .join('\n')
  const rgbProperties = COLOR_NAMES
    .map(name => `  --gcu-${name}-rgb:${rgbChannels(colors[name])};`)
    .join('\n')

  return `${CSS_START}\n:root,.gcu-theme,[data-gcu-theme="light"]{
${semanticProperties}
${rgbProperties}
  --gcu-text:var(--gcu-dark);--gcu-muted:var(--gcu-secondary);--gcu-surface:#fff;--gcu-surface-subtle:var(--gcu-canvas);
  --gcu-border:#e5e7eb;--gcu-focus:rgba(var(--gcu-primary-rgb),.2);--gcu-radius:10px;
  --gcu-shadow:0 1px 3px 0 rgb(0 0 0/.1),0 1px 2px -1px rgb(0 0 0/.1);--gcu-font:"Inter",-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;
}
[data-gcu-theme="dark"],.app-skin-dark{
  --gcu-text:#b1b4c0;--gcu-muted:#9aa4b2;--gcu-surface:#121a2d;--gcu-surface-subtle:#0f172a;
  --gcu-border:#1b2436;--gcu-focus:rgba(103,128,235,.28);--gcu-shadow:0 0 20px rgb(0 0 0/.5);
}
/* Dark theme override: .gcu-theme may re-declare light vars in its own scope. */
.app-skin-dark .gcu-theme:not([data-gcu-theme="light"]){
  --gcu-text:#b1b4c0;--gcu-muted:#9aa4b2;--gcu-surface:#121a2d;--gcu-surface-subtle:#0f172a;
  --gcu-border:#1b2436;--gcu-focus:rgba(103,128,235,.28);--gcu-shadow:0 0 20px rgb(0 0 0/.5);
}
${CSS_END}`
}

function replaceGeneratedCss(content, generatedBlock) {
  const start = content.indexOf(CSS_START)
  const endMarker = content.indexOf(CSS_END)

  if (start !== -1 || endMarker !== -1) {
    if (start === -1 || endMarker === -1 || endMarker < start) {
      throw new Error('grancrm-ui.css has an incomplete generated token block')
    }
    return `${content.slice(0, start)}${generatedBlock}${content.slice(endMarker + CSS_END.length)}`
  }

  const rootStart = content.indexOf(':root')
  const themeAnchor = content.indexOf('\n.gcu-theme{', rootStart)
  if (rootStart === -1 || themeAnchor === -1) {
    throw new Error('Could not find the legacy token block in grancrm-ui.css')
  }
  return `${content.slice(0, rootStart)}${generatedBlock}\n${content.slice(themeAnchor + 1)}`
}

function readExpectedArtifacts(root = ROOT) {
  const colors = readSemanticColors(root)
  return {
    ts: renderGeneratedTypeScript(colors),
    scss: renderGeneratedScss(colors),
    css: renderGeneratedCss(colors),
  }
}

export function checkArtifacts(root = ROOT) {
  const expected = readExpectedArtifacts(root)
  const paths = {
    ts: join(root, 'src/generated/semantic-colors.ts'),
    scss: join(root, 'scss/themes/_semantic-tokens.generated.scss'),
    css: join(root, 'src/styles/grancrm-ui.css'),
  }
  const mismatches = []

  for (const kind of ['ts', 'scss']) {
    let actual
    try {
      actual = readFileSync(paths[kind], 'utf8')
    } catch {
      actual = null
    }
    if (actual !== expected[kind]) {
      mismatches.push(paths[kind])
    }
  }

  let css
  try {
    css = readFileSync(paths.css, 'utf8')
  } catch {
    css = ''
  }
  const start = css.indexOf(CSS_START)
  const end = css.indexOf(CSS_END)
  const actualCssBlock = start !== -1 && end !== -1 && end >= start
    ? css.slice(start, end + CSS_END.length)
    : null
  if (actualCssBlock !== expected.css) {
    mismatches.push(`${paths.css} (${CSS_START} block)`)
  }

  const tokensTs = readFileSync(join(root, 'src/tokens.ts'), 'utf8')
  if (!tokensTs.includes("from './generated/semantic-colors'")) {
    mismatches.push(`${join(root, 'src/tokens.ts')} (generated semantic import)`)
  }

  const bsCustomVariables = readFileSync(join(root, 'scss/themes/_bs-custom-variables.scss'), 'utf8')
  if (!bsCustomVariables.includes('@import "./semantic-tokens.generated";')) {
    mismatches.push(`${join(root, 'scss/themes/_bs-custom-variables.scss')} (generated semantic import)`)
  }

  return mismatches
}

export function writeArtifacts(root = ROOT) {
  const expected = readExpectedArtifacts(root)
  const tsPath = join(root, 'src/generated/semantic-colors.ts')
  const scssPath = join(root, 'scss/themes/_semantic-tokens.generated.scss')
  const cssPath = join(root, 'src/styles/grancrm-ui.css')

  mkdirSync(dirname(tsPath), { recursive: true })
  mkdirSync(dirname(scssPath), { recursive: true })
  writeFileSync(tsPath, expected.ts)
  writeFileSync(scssPath, expected.scss)

  const css = readFileSync(cssPath, 'utf8')
  writeFileSync(cssPath, replaceGeneratedCss(css, expected.css))
}

if (resolve(process.argv[1] ?? '') === resolve(fileURLToPath(import.meta.url))) {
  if (process.argv.includes('--check')) {
    const mismatches = checkArtifacts()
    if (mismatches.length > 0) {
      console.error('Semantic token drift detected:')
      for (const mismatch of mismatches) console.error(`- ${mismatch}`)
      process.exitCode = 1
    } else {
      console.log('Semantic token artifacts are up to date.')
    }
  } else {
    writeArtifacts()
    console.log('Generated semantic token artifacts.')
  }
}
